Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'spec/**/*'
    - 'test/**'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
